// Height options for dropdown (4'6" to 7'0")
export const HEIGHT_OPTIONS = [
  { value: "4'6\"", label: "4'6\" (137 cm)" },
  { value: "4'7\"", label: "4'7\" (140 cm)" },
  { value: "4'8\"", label: "4'8\" (142 cm)" },
  { value: "4'9\"", label: "4'9\" (145 cm)" },
  { value: "4'10\"", label: "4'10\" (147 cm)" },
  { value: "4'11\"", label: "4'11\" (150 cm)" },
  { value: "5'0\"", label: "5'0\" (152 cm)" },
  { value: "5'1\"", label: "5'1\" (155 cm)" },
  { value: "5'2\"", label: "5'2\" (157 cm)" },
  { value: "5'3\"", label: "5'3\" (160 cm)" },
  { value: "5'4\"", label: "5'4\" (163 cm)" },
  { value: "5'5\"", label: "5'5\" (165 cm)" },
  { value: "5'6\"", label: "5'6\" (168 cm)" },
  { value: "5'7\"", label: "5'7\" (170 cm)" },
  { value: "5'8\"", label: "5'8\" (173 cm)" },
  { value: "5'9\"", label: "5'9\" (175 cm)" },
  { value: "5'10\"", label: "5'10\" (178 cm)" },
  { value: "5'11\"", label: "5'11\" (180 cm)" },
  { value: "6'0\"", label: "6'0\" (183 cm)" },
  { value: "6'1\"", label: "6'1\" (185 cm)" },
  { value: "6'2\"", label: "6'2\" (188 cm)" },
  { value: "6'3\"", label: "6'3\" (191 cm)" },
  { value: "6'4\"", label: "6'4\" (193 cm)" },
  { value: "6'5\"", label: "6'5\" (196 cm)" },
  { value: "6'6\"", label: "6'6\" (198 cm)" },
  { value: "6'7\"", label: "6'7\" (201 cm)" },
  { value: "6'8\"", label: "6'8\" (203 cm)" },
  { value: "6'9\"", label: "6'9\" (206 cm)" },
  { value: "6'10\"", label: "6'10\" (208 cm)" },
  { value: "6'11\"", label: "6'11\" (211 cm)" },
  { value: "7'0\"", label: "7'0\" (213 cm)" },
]

// Preferred Age Range options
export const PREF_AGE_OPTIONS = [
  { value: "doesnt_matter", label: "Doesn't matter" },
  { value: "same_age", label: "Same age (±1 year)" },
  { value: "1-3_younger", label: "1-3 years younger" },
  { value: "1-3_older", label: "1-3 years older" },
  { value: "3-5_younger", label: "3-5 years younger" },
  { value: "3-5_older", label: "3-5 years older" },
  { value: "5+_younger", label: "5+ years younger" },
  { value: "5+_older", label: "5+ years older" },
]

// Preferred Income options (minimum)
export const PREF_INCOME_OPTIONS = [
  { value: "doesnt_matter", label: "Doesn't matter" },
  { value: "50k+", label: "$50k+" },
  { value: "75k+", label: "$75k+" },
  { value: "100k+", label: "$100k+" },
  { value: "150k+", label: "$150k+" },
  { value: "200k+", label: "$200k+" },
]

// Preferred Location options
export const PREF_LOCATION_OPTIONS = [
  { value: "doesnt_matter", label: "Doesn't matter" },
  { value: "usa", label: "Anywhere in USA" },
  // Specific regions
  { value: "bay_area", label: "Bay Area, California" },
  { value: "southern_california", label: "Southern California (LA, San Diego)" },
  // States
  { value: "california", label: "California" },
  { value: "texas", label: "Texas" },
  { value: "new_york", label: "New York" },
  { value: "new_jersey", label: "New Jersey" },
  { value: "washington", label: "Washington" },
  { value: "illinois", label: "Illinois" },
  { value: "massachusetts", label: "Massachusetts" },
  { value: "georgia", label: "Georgia" },
  { value: "virginia", label: "Virginia" },
  { value: "north_carolina", label: "North Carolina" },
  { value: "pennsylvania", label: "Pennsylvania" },
  { value: "florida", label: "Florida" },
  { value: "colorado", label: "Colorado" },
  { value: "arizona", label: "Arizona" },
  { value: "maryland", label: "Maryland" },
  { value: "ohio", label: "Ohio" },
  { value: "michigan", label: "Michigan" },
  { value: "minnesota", label: "Minnesota" },
  { value: "indiana", label: "Indiana" },
  { value: "missouri", label: "Missouri" },
  { value: "other_state", label: "Other US State" },
  { value: "open_to_relocation", label: "Open to relocation" },
]

// Education/Qualification options for profile (US-based degrees)
// Level: 1=High School, 2=Undergrad, 3=Masters/Professional, 4=Doctorate
export const QUALIFICATION_OPTIONS = [
  { value: "high_school", label: "High School Diploma", level: 1 },
  { value: "associates", label: "Associate's Degree (AA, AS)", level: 1 },
  // Undergrad (Bachelor's)
  { value: "bachelors_arts", label: "Bachelor of Arts (BA)", level: 2 },
  { value: "bachelors_science", label: "Bachelor of Science (BS)", level: 2 },
  { value: "bachelors_eng", label: "Bachelor of Engineering (BE, BSE)", level: 2 },
  { value: "bachelors_cs", label: "Bachelor of Science - Computer Science (BS CS)", level: 2 },
  { value: "bba", label: "Bachelor of Business Administration (BBA)", level: 2 },
  { value: "bfa", label: "Bachelor of Fine Arts (BFA)", level: 2 },
  { value: "bsn", label: "Bachelor of Science in Nursing (BSN)", level: 2 },
  // Masters
  { value: "masters_arts", label: "Master of Arts (MA)", level: 3 },
  { value: "masters_science", label: "Master of Science (MS)", level: 3 },
  { value: "masters_eng", label: "Master of Engineering (MEng)", level: 3 },
  { value: "masters_cs", label: "Master of Science - Computer Science (MS CS)", level: 3 },
  { value: "mba", label: "Master of Business Administration (MBA)", level: 3 },
  { value: "mfa", label: "Master of Fine Arts (MFA)", level: 3 },
  { value: "mph", label: "Master of Public Health (MPH)", level: 3 },
  { value: "msw", label: "Master of Social Work (MSW)", level: 3 },
  // Professional Degrees
  { value: "md", label: "Doctor of Medicine (MD)", level: 4 },
  { value: "do", label: "Doctor of Osteopathic Medicine (DO)", level: 4 },
  { value: "dds", label: "Doctor of Dental Surgery (DDS, DMD)", level: 4 },
  { value: "pharmd", label: "Doctor of Pharmacy (PharmD)", level: 4 },
  { value: "jd", label: "Juris Doctor (JD) - Law", level: 4 },
  { value: "cpa", label: "Certified Public Accountant (CPA)", level: 3 },
  // Doctorate
  { value: "phd", label: "Doctor of Philosophy (PhD)", level: 4 },
  { value: "edd", label: "Doctor of Education (EdD)", level: 4 },
  { value: "psyd", label: "Doctor of Psychology (PsyD)", level: 4 },
  { value: "other", label: "Other", level: 2 },
]

// Preferred Education options for partner preferences (US-based)
// type: 'level' = matches this level or higher, 'category' = specific category only
export const PREF_EDUCATION_OPTIONS = [
  { value: "doesnt_matter", label: "Doesn't matter", type: "any" },
  { value: "bachelors", label: "Bachelor's or higher", type: "level", minLevel: 2 },
  { value: "masters", label: "Master's or higher", type: "level", minLevel: 3 },
  // Engineering
  { value: "eng_bachelors", label: "Engineering - Bachelor's (BE, BSE)", type: "category", categories: ["bachelors_eng"] },
  { value: "eng_masters", label: "Engineering - Master's (MEng, MS)", type: "category", categories: ["masters_eng"] },
  // Computer Science
  { value: "cs_bachelors", label: "Computer Science - Bachelor's (BS CS)", type: "category", categories: ["bachelors_cs"] },
  { value: "cs_masters", label: "Computer Science - Master's (MS CS)", type: "category", categories: ["masters_cs"] },
  // Medical / Healthcare
  { value: "medical", label: "Medical (MD, DO)", type: "category", categories: ["md", "do"] },
  { value: "healthcare", label: "Healthcare (BSN, PharmD, DDS)", type: "category", categories: ["bsn", "pharmd", "dds"] },
  // Business / Professional
  { value: "mba", label: "MBA", type: "category", categories: ["mba"] },
  { value: "cpa", label: "CPA (Certified Public Accountant)", type: "category", categories: ["cpa"] },
  { value: "law", label: "Law (JD)", type: "category", categories: ["jd"] },
  { value: "doctorate", label: "Doctorate (PhD, EdD, PsyD)", type: "category", categories: ["phd", "edd", "psyd"] },
]

// Hobbies options (Shaadi.com style)
export const HOBBIES_OPTIONS = [
  'Art & Crafts',
  'Blogging',
  'Board Games',
  'Cooking',
  'Dancing',
  'DIY Projects',
  'Gardening',
  'Gaming',
  'Listening to Music',
  'Movies & TV Shows',
  'Musical Instruments',
  'Painting',
  'Photography',
  'Playing Cards',
  'Podcasts',
  'Poetry',
  'Reading',
  'Singing',
  'Social Media',
  'Travelling',
  'Video Making',
  'Volunteering',
  'Writing',
]

// Fitness & Sports options
export const FITNESS_OPTIONS = [
  'Badminton',
  'Basketball',
  'Biking / Cycling',
  'Cricket',
  'Football / Soccer',
  'Golf',
  'Gym / Weight Training',
  'Hiking / Trekking',
  'Martial Arts',
  'Meditation',
  'Pilates',
  'Running / Jogging',
  'Swimming',
  'Table Tennis',
  'Tennis',
  'Walking',
  'Yoga',
  'Zumba / Aerobics',
]

// Interests options
export const INTERESTS_OPTIONS = [
  'Astronomy',
  'Automobiles',
  'Business & Investing',
  'Cars & Bikes',
  'Current Affairs',
  'Environment & Sustainability',
  'Fashion & Style',
  'Finance & Stocks',
  'Food & Cuisine',
  'Health & Wellness',
  'History',
  'Home Decor',
  'Languages',
  'Nature & Wildlife',
  'News & Politics',
  'Personal Development',
  'Pets & Animals',
  'Psychology',
  'Science & Technology',
  'Spirituality',
  'Sports',
  'Startups',
  'Travel & Adventure',
]

// Occupation options for profile
export const OCCUPATION_OPTIONS = [
  { value: "software_engineer", label: "Software Engineer / Developer" },
  { value: "data_scientist", label: "Data Scientist / ML Engineer" },
  { value: "product_manager", label: "Product Manager" },
  { value: "business_analyst", label: "Business Analyst" },
  { value: "doctor", label: "Doctor / Physician" },
  { value: "dentist", label: "Dentist" },
  { value: "nurse", label: "Nurse / Healthcare" },
  { value: "pharmacist", label: "Pharmacist" },
  { value: "lawyer", label: "Lawyer / Attorney" },
  { value: "ca_accountant", label: "CA / CPA / Accountant" },
  { value: "consultant", label: "Consultant" },
  { value: "banker", label: "Banker / Finance" },
  { value: "teacher_professor", label: "Teacher / Professor" },
  { value: "researcher", label: "Researcher / Scientist" },
  { value: "government", label: "Government Employee" },
  { value: "business_owner", label: "Business Owner / Entrepreneur" },
  { value: "student", label: "Student" },
  { value: "homemaker", label: "Homemaker" },
  { value: "other", label: "Other" },
]

// US Universities (Top 200+ universities sorted alphabetically)
export const US_UNIVERSITIES = [
  "Other (specify below)",
  // Top National Universities
  "Arizona State University",
  "Auburn University",
  "Baylor University",
  "Boston College",
  "Boston University",
  "Brandeis University",
  "Brigham Young University",
  "Brown University",
  "California Institute of Technology (Caltech)",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Clemson University",
  "Colorado State University",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Drexel University",
  "Duke University",
  "Emory University",
  "Florida International University",
  "Florida State University",
  "Fordham University",
  "George Mason University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology (Georgia Tech)",
  "Harvard University",
  "Howard University",
  "Indiana University Bloomington",
  "Iowa State University",
  "Johns Hopkins University",
  "Kansas State University",
  "Lehigh University",
  "Louisiana State University",
  "Loyola University Chicago",
  "Marquette University",
  "Massachusetts Institute of Technology (MIT)",
  "Michigan State University",
  "New York University (NYU)",
  "North Carolina State University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Oregon State University",
  "Penn State University",
  "Pepperdine University",
  "Princeton University",
  "Purdue University",
  "Rensselaer Polytechnic Institute",
  "Rice University",
  "Rutgers University",
  "San Diego State University",
  "San Jose State University",
  "Santa Clara University",
  "Southern Methodist University",
  "Stanford University",
  "Stony Brook University (SUNY)",
  "Syracuse University",
  "Temple University",
  "Texas A&M University",
  "Texas Tech University",
  "Tufts University",
  "Tulane University",
  "UC Berkeley",
  "UC Davis",
  "UC Irvine",
  "UC Los Angeles (UCLA)",
  "UC San Diego (UCSD)",
  "UC Santa Barbara",
  "UC Santa Cruz",
  "University at Buffalo (SUNY)",
  "University of Alabama",
  "University of Arizona",
  "University of Arkansas",
  "University of Central Florida",
  "University of Chicago",
  "University of Cincinnati",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Delaware",
  "University of Denver",
  "University of Florida",
  "University of Georgia",
  "University of Houston",
  "University of Illinois Chicago",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of Missouri",
  "University of Nebraska-Lincoln",
  "University of Nevada, Las Vegas",
  "University of New Mexico",
  "University of North Carolina at Chapel Hill",
  "University of Notre Dame",
  "University of Oklahoma",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of San Diego",
  "University of San Francisco",
  "University of South Carolina",
  "University of South Florida",
  "University of Southern California (USC)",
  "University of Tennessee",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Utah",
  "University of Vermont",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Villanova University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington State University",
  "Washington University in St. Louis",
  "Wayne State University",
  "West Virginia University",
  "Worcester Polytechnic Institute",
  "Yale University",
]
