// Sub-community list organized by religion
// Based on Shaadi.com's community directory

export const RELIGIONS = [
  'Hindu',
  'Muslim',
  'Sikh',
  'Christian',
  'Jain',
  'Buddhist',
  'Parsi',
  'Jewish',
  'Other',
] as const;

export type Religion = typeof RELIGIONS[number];

export const SUB_COMMUNITIES: Record<string, string[]> = {
  Hindu: [
    'Agarwal',
    'Arora',
    'Bania',
    'Brahmin - Bengali',
    'Brahmin - Deshastha',
    'Brahmin - Garhwali',
    'Brahmin - Gour',
    'Brahmin - Goswami',
    'Brahmin - Gujarati',
    'Brahmin - Havyaka',
    'Brahmin - Hindi',
    'Brahmin - Iyer',
    'Brahmin - Iyengar',
    'Brahmin - Kanyakubja',
    'Brahmin - Karhade',
    'Brahmin - Kokanastha',
    'Brahmin - Kulin',
    'Brahmin - Madhwa',
    'Brahmin - Maithil',
    'Brahmin - Marathi',
    'Brahmin - Namboodiri',
    'Brahmin - Punjabi',
    'Brahmin - Sanketi',
    'Brahmin - Saraswat',
    'Brahmin - Saryuparin',
    'Brahmin - Smartha',
    'Brahmin - Tamil',
    'Brahmin - Telugu',
    'Brahmin - Tyagi',
    'Brahmin - Vaidiki',
    'Brahmin - Other',
    'Bunt',
    'Chettiar',
    'Devanga',
    'Ezhava',
    'Gowda',
    'Gupta',
    'Jat',
    'Kamma',
    'Kapu',
    'Kayastha',
    'Khandayat',
    'Khatri',
    'Kshatriya',
    'Kurmi',
    'Lingayat',
    'Maheshwari',
    'Maratha',
    'Marwari',
    'Meena',
    'Mudaliar',
    'Nadar',
    'Naidu',
    'Nair',
    'Patel',
    'Pillai',
    'Rajput',
    'Reddy',
    'Scheduled Caste',
    'Scheduled Tribe',
    'Sindhi',
    'Sonar',
    'Teli',
    'Vaish',
    'Vaishnav',
    'Vaishya',
    'Vanniyar',
    'Velama',
    'Vishwakarma',
    'Vokkaliga',
    'Vysya',
    'Yadav',
    'Other',
  ],
  Muslim: [
    'Ansari',
    'Arain',
    'Awan',
    'Bohra',
    'Dawoodi Bohra',
    'Hanafi',
    'Jat Muslim',
    'Khoja',
    'Lebbai',
    'Malik',
    'Mapila',
    'Memon',
    'Mughal',
    'Pathan',
    'Qureshi',
    'Rajput Muslim',
    'Rowther',
    'Shafi',
    'Sheikh',
    'Shia',
    'Shia Imami Ismaili',
    'Shia Ithna Ashariyyah',
    'Siddiqui',
    'Sunni',
    'Syed',
    'Other',
  ],
  Sikh: [
    'Arora',
    'Bhatia',
    'Gursikh',
    'Jat',
    'Kamboj',
    'Kesadhari',
    'Khatri',
    'Labana',
    'Lubana',
    'Majhabi',
    'Nai',
    'Ramdasia',
    'Ramgarhia',
    'Ravidasia',
    'Saini',
    'Tonk Kshatriya',
    'Other',
  ],
  Christian: [
    'Anglo Indian',
    'Born Again',
    'Brethren',
    'Catholic',
    'Church of North India (CNI)',
    'Church of South India (CSI)',
    'Evangelical',
    'Jacobite',
    'Knanaya',
    'Latin Catholic',
    'Marthoma',
    'Methodist',
    'Orthodox',
    'Pentecostal',
    'Protestant',
    'Roman Catholic',
    'Seventh Day Adventist',
    'Syrian Catholic',
    'Syrian Orthodox',
    'Other',
  ],
  Jain: [
    'Agarwal',
    'Bisa Oswal',
    'Dasa Oswal',
    'Digambar',
    'Khandelwal',
    'Oswal',
    'Porwal',
    'Shwetamber',
    'Terapanthi',
    'Other',
  ],
  Buddhist: [
    'Mahayana',
    'Theravada',
    'Tibetan Buddhist',
    'Neo Buddhist',
    'Other',
  ],
  Parsi: [
    'Irani',
    'Parsi',
    'Other',
  ],
  Jewish: [
    'Ashkenazi',
    'Sephardic',
    'Orthodox',
    'Reform',
    'Conservative',
    'Other',
  ],
  Other: [
    'Inter-Religion',
    'No Religion',
    'Spiritual',
    'Other',
  ],
};

// Helper function to get sub-communities for a religion
export function getSubCommunities(religion: string): string[] {
  return SUB_COMMUNITIES[religion] || SUB_COMMUNITIES['Other'];
}

// All communities flattened (for partner preference multi-select)
export function getAllCommunities(): string[] {
  const allCommunities: string[] = [];
  Object.values(SUB_COMMUNITIES).forEach(communities => {
    communities.forEach(community => {
      if (!allCommunities.includes(community) && community !== 'Other') {
        allCommunities.push(community);
      }
    });
  });
  return allCommunities.sort();
}
